#goal: To run end to end devsecops CICD pipeline
name : devsecops_deployment

on:
    push:
        branches: [master]


jobs:
    code-quality:
        uses: ./.github/workflows/code-quality.yml

    git-leaks-check:
        uses: ./.github/workflows/secret-scanning.yml

    dependency-checks:
        uses: ./.github/workflows/dependency-scan.yml

    docker-file-and-image-checks:
        uses: ./.github/workflows/docker-scan.yml
    
    sonar-qube-scan:
        uses: ./.github/workflows/sonar-scan.yml
        secrets: inherit
    
    code-tests:
        uses: ./.github/workflows/code-tests.yml
    
    docker-push:
        uses: ./.github/workflows/docker-push.yml
        secrets: inherit
        needs: [code-quality, git-leaks-check, dependency-checks, docker-file-and-image-checks, sonar-qube-scan, code-tests]

    code-deploy:
        uses: ./.github/workflows/deploy.yml
        secrets: inherit
        needs: [docker-push]
    
    DAST:
        uses: ./.github/workflows/dast.yml
        secrets: inherit
        needs: [code-deploy]