name: Kyverno Policy Validation

on:
    workflow_call:

jobs:
  kyverno:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v7

      - name: Install Kyverno CLI
        uses: kyverno/action-install-cli@v0.2.0
        with:
          release: 'v1.14.0'

      - name: Validate deployment manifests for app label
        run: |
          find k8s -name '*deployment*.yml' | while read file; do
          kyverno apply kyverno-policy/app-label.yml --resource "$file"
          done

      - name: Validate manifests
        run: |
          find k8s -name '*deployment*.yml' | while read file; do
          kyverno apply kyverno-policy/not-latest-image-tag.yml --resource "$file"
          done
