name: Kyverno Policy Validation

on:
    workflow_call:

jobs:
  kyverno:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v7

      - name: Setup Kyverno CLI
        uses: kyverno/action-install-cli@v0.2.0

      - name: Validate manifests
        run: |
          kyverno apply kyverno-policy/ --resource k8s/
