name: sonar-scan

on:
    workflow_call

jobs:
    node-code-quality:
        runs-on: self-hosted
        steps:
            - name: git checkout step
              uses: actions/checkout@v7
        
            - name: sonar-scan-step
              uses: SonarSource/sonarqube-scan-action@v8.2.0
              with:
                skipSignatureVerification: true
              env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
